POST http://localhost:5302/projects/new-project
Content-Type: application/json

{
  "project_name": "To Do List Project",
  "project_description": "Come up with an interactive UI that is well intergrated with backend-API",
  "project_end_date": "2024-06-05"
}

### Fetch All Projects Created
GET http://localhost:5302/projects/all-projects
Content-Type: application/json

### Update Project by ID
PUT http://localhost:5302/projects/update-project/0e7ded6c-bd0c-4d73-87e2-24d3d8c38d5d
Content-Type: application/json

{
  "project_name": "Project Management System",
  "project_description": "Design an MSSQL database backend API",
  "project_end_date": "2025-05-10"
}

### Delete project from database
DELETE http://localhost:5302/projects/delete-project/0e7ded6c-bd0c-4d73-87e2-24d3d8c38d5d
Content-Type: application/json