# POST Request
POST http://localhost:5300/users/create
Content-Type: application/json

{
    "FirstName": "Salome",
    "LastName": "Mwati",
    "phone_number": "0794776976",
    "email":  "sonniewati38@gmail.com",
    "password": "6767",
    "user_image": "image1",
    "project_id":null,
    "isAssignedProject": ""
}
