# POST Request
POST http://localhost:5300/users/create
Content-Type: application/json

{
    "FirstName": "Clinton",
    "LastName": "Omari",
    "phone_number": "0789374859",
    "email":  "clintonarani@gmail.com",
    "password": "12345678",
    "user_image": "image1",
    "project_id":"2",
    "isAssignedProject": "true"
}